### ISSUE TITLE
lift, def etc shortcuts not working.

### ISSUE THREAD

**Issue by jeetu7** [stoand/kakoune-idris#1]
First of all thanks for making this plugin. I was not expecting Idris2 support on kak.
I can confirm that idris2 is working fine on my machine. 
I have also added the mentioned thing in kakrc.
I can see the menu of Idris things on pressing minus, but the def, lift etc are not working. Kakone and Idris2 are also recent built on my system.

**Comment by jeetu7** [comment]
Some info

kakoune-idris ➤ which idris2                                                                                                    
/home/jeetu/.idris2/bin/idris2

.kakoune-idris ➤ which nodemon 
/home/jeetu/items/node-v12.16.2-linux-x64/bin/nodemon

.kakoune-idris ➤ nodemon ide-mode-test.js                                                                                        
[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ide-mode-test.js`
assert.js:100
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Attempt to load wrong file should display command failed
    at Object.<anonymous> (/home/jeetu/.kakoune-idris/ide-mode-test.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 'info "Error loading file NonExisting.idr: File Not Found"',
  expected: 'echo "Command failed"',
  operator: '=='
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by stoand** [comment]
Looks like the IDE protocol changed. I've updated the code to work with the `2.0` protocol. 

Also, I've replaced the ultra hacky regexp parser with a real s-expr parser.

48504c5c189196758a0660de2dc89d09539329ee

**Comment by jeetu7** [comment]
Thanks.
