### ISSUE TITLE
The type of holes in interface implementations gives "undefined"

### ISSUE THREAD

**Issue by malte-v** [stoand/kakoune-idris#7]
```idris
data Foo = MkFoo

Eq Foo where
  x == y = ?arst
```

Using the type-of action on `?arst` just shows "undefined".

**Comment by stoand** [comment]
I'm not sure the problem is with this plugin itself.

This plugin is merely a wrapper around Idris 2's IDE protocol. 

Idris 2 itself is doing the heavy lifting here, so you may want to bring up the issue in that repo: https://github.com/idris-lang/Idris2

**Comment by stoand** [comment]
Disregard the previous comment. 

Apparently, providing a line and column parameter to the `type-of` ide command will randomly break the output.

Removing the line and column params fixed the issue.

http://docs.idris-lang.org/en/latest/reference/ide-protocol.html
